name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  json_annotation: 4.9.0
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  get_it: ^8.0.3
  injectable: ^2.5.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  build_runner: 2.4.15
  injectable_generator:

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
      - asset: assets/fonts/Lato-Regular.ttf
        weight: 400
